name: tf-plan

on:
  push:
    branches: aws
    paths:
      - '**.tf'
      - '**.tfvars'

env:
    AWS_REGION : "us-east-1"

jobs:
  terraform-plan:
        # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    
    steps:
        - uses: actions/checkout@v3.6.0

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            audience: sts.amazonaws.com
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::851725305616:role/gha_oidc_role

        - name: Install Terraform
          run: | 
                terraform --version
                terraform init
                terraform apply -auto-approve
                pwd
                ls -al